title: Faiz Aditya Dhananjaya
#logo: /assets/img/headshot_circle.png
description: Hello my name is Faiz Aditya Dhananjaya, people always call me Faiz. Currently i am pursuing my degree at Dian Nuswantoro University majoring in informatics engineering, I am interested on cybersecurity blue team which is forensic because it sound cool
#show_downloads: true
theme: jekyll-theme-minimal
